[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[dependency-groups]
dev = [
    "mypy (>=1.18.2,<2)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=6.0.1,<7.0.0)"
]

[project]
dependencies = [
    "connectrpc (>=0.11.1,<0.12)",
    "protobuf-py (>=0.1.1,<0.2)",
]
requires-python = ">=3.10,<4"
name = "elimity-insights-sdk"
version = "1.0.0a0"

[tool.poetry]
packages = [
    { from = "gen", include = "elimity" },
    { from = "src", include = "elimity_insights_sdk" }
]
