jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/elimity-com/insights-sdk:${{ github.run_id }}

on: workflow_dispatch
